TILE_SIZE = 48
FPS = 30
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

COLORS = {
    "background": (40, 40, 50),
    "panel_bg": (55, 55, 65),
    "wall": (100, 80, 60),
    "floor": (210, 190, 160),
    "player": (0, 120, 200),
    "player_on_goal": (0, 180, 220),
    "box": (200, 150, 50),
    "box_on_goal": (0, 180, 80),
    "goal": (220, 60, 60),
    "outside": (30, 30, 30),
    "text": (230, 230, 230),
    "text_dim": (150, 150, 150),
    "text_dark": (60, 60, 60),
    "button_bg": (70, 130, 200),
    "button_hover": (90, 150, 220),
    "button_disabled": (80, 80, 90),
    "checkbox_bg": (70, 70, 80),
    "checkbox_check": (100, 200, 120),
    "selected_row": (70, 100, 140),
    "optimal_row": (40, 100, 60),
    "failure_row": (80, 60, 60),
    "header_bg": (50, 50, 60),
    "slider_track": (80, 80, 90),
    "slider_handle": (100, 180, 220),
    "success_text": (100, 220, 120),
    "failure_text": (220, 100, 100),
    "optimal_text": (255, 215, 0),
    "white": (255, 255, 255),
    "black": (0, 0, 0),
    "progress_pending": (120, 120, 130),
    "progress_running": (255, 180, 50),
    "progress_done": (100, 200, 120),
}

STRINGS = {
    "app_title": "Sokoban - Comparador de Algoritmos",
    "level_select_title": "Seleccionar Nivel",
    "load_file": "Cargar archivo...",
    "play": "Jugar",
    "back_to_selector": "Volver al selector",
    "solve": "Resolver",
    "replay": "Reproducir",
    "back": "Volver",
    "moves": "Movimientos",
    "solved": "Nivel resuelto!",
    "undo": "Deshacer (Z)",
    "reset": "Reiniciar (R)",
    "comparing_progress": "Resolviendo...",
    "method_done": "Completado",
    "method_running": "En ejecucion...",
    "method_pending": "Pendiente",
    "col_algorithm": "Algoritmo",
    "col_heuristic": "Heuristica",
    "col_result": "Resultado",
    "col_cost": "Costo",
    "col_time": "Tiempo (s)",
    "col_nodes": "Nodos Exp.",
    "col_frontier": "Frontera",
    "col_steps": "Pasos",
    "result_success": "Exito",
    "result_failure": "Fallo",
    "optimal_marker": "* Optimo",
    "speed": "Velocidad",
    "replay_controls": "Espacio: pausa | Flechas: paso | Slider: velocidad",
    "play_controls": "Flechas: mover | Z: deshacer | R: reiniciar",
    "no_methods_selected": "Seleccione al menos un metodo",
    "step_label": "Paso {} / {}",
    "no_file_selected": "No se selecciono archivo",
    "default_collection": "Coleccion por defecto",
    "select_solution": "Seleccione una solucion exitosa",
    "cancel": "Cancelar",
    "paused": "Pausado",
    "playing": "Reproduciendo",
}
