from __future__ import annotations

import argparse
from collections import deque
from dataclasses import dataclass
from pathlib import Path

from src.model.board_layout import BoardLayout, DIRECTIONS
from src.model.state import SokobanState

BOARD_CHARS = set("#-.$*@+")
OUTSIDE_CHAR = "-"
DEFAULT_EXPECTED_LEVELS = 50

ORIGINAL01_COLLECTION = """Collection: Original01
Author: DrFogh
Mail: bjertrup58@gmail.com
Url: www.sokoban.dk
Firstdate: 2013-07-31
Lastdate: 2015-11-19

50 original puzzles arranged roughly chronologically.
A few previously published variations only differing slightly from the puzzles here are omitted.

The puzzles can be freely distributed.

Plese quote me as the original author with name, email and url.

###########
#---------#
#-$-$@$-$-#
#--$-$-$--#
#-$-$-$-$-#
#--$-$-$--#
#####$##$##
-#.....#-#
-#....*#-#
-#...*---#
-#....-###
-########
Title: 001 Abedlike
Comment: Tribute to Howard Abed who made a lot of levels with this basic design. Looking through my old designs this seems to be my first original attempt at making a Sokoban puzzle.
Previously published: Accumulated1
Date: 2013-07-31

-------######
-####--#----#
-#-@####-##-##
##-$#--#...--#
#--$-$-#.#.#-#
#-$-$--$...#-#
##-$--$-##-#-#
-##-###----#-#
--#---######-#
--###--------#
----##########
Title: 002 Forgotten One
Previously published: Accumulated1
Date: 2014-08-23

---###
---#.#
---#.#
####.##
#--#.@##
#--#.--##
#--#.$$-#
#-$-#$--#
#---#-$.#
##-$--$-#
-#----###
-######
Title: 003 My First Autogenerated Level
Comment: Generated 50 levels. Kept one and edited a little. Not too bad.
Previously published: Sokoban.dk(Lines), Accumulated1
Date: 2014-10-04

#########################
#--.**.-*...$.***-..*.$-#
#-.$-$-.$---*-$--*$-$-*-#
#.$$-$*-*--.$.$-.-*-$-$.#
#.$---*-*--.$.$-.-*-$-$.#
#.$---*-*--.$.$-.-*-$-$.#
#.$$$$*-*--.$.$-.-*-$-$.#
#-*---$.$$--*-$--*$-$-+-#
#-$...*-.***-.***-..*.$-#
#########################
Title: 004 Audi
Comment: Looks depends on the skin.
Previously published: SokobanOnline.com, Sokoban.dk, Accumulated1
Date: 2014-11-08

##############################
#--------#-----#--###--#-----#
#--$--$-$---$--#$-##-$-$$-$--#
#-$$######$-#-$---#----#--#$-#
#--------#--#--#-$----##--#--#
#--$-$-$-#$-#$-#$-#$$-##-$#$-#
#######$-#--#-----#----#--#--#
#--$---$-#$-$--#$-##-$-$$$$--#
#--#-----#-----#--###--#-----#
#-.########################$##
#.........-----##-----#--##--#
#........#-$$-$-#--$$-$$--#$-#
#........#--##-$---#--#--$#--#
#........#-$$---#-$#$-#$-$---#
#........#-$----#$--$-#--$$--#
#........#-$##-$----$-#--#-$-#
#........#--$-$-#$-#--$--#---#
#........#----@##--#--#--##--#
##############################
Title: 005 Sokoban Aenigma
Author: Brian Kent + Tyge Fogh
Comment: Aenigma 42. Not a sharpened level, but a heavily influenced remake with several structural changes with influence on gameplay. Added 60 boxes.
Previously published: Sokoban.dk, Accumulated1
Date: 2014-11-09

####################
#------------------#
#-**$***$$***$$***-#
#-*.-*..$-.*.-$..*-#
#-*.-*..$-.*.-$..*-#
#-**$***$$***$$***-#
#----------------@-#
####################
Title: 006 Not difficult. Just The Right Order
Comment: A visual modification a year later
Previously published: Accumulated1
Date: 2014-11-09

---------####
##########--#
#-----------#
#-$$-$-$-$$-#
#--#######--#
#-$#...*.#$-#
#--#...*.#--#
#-$#..@$-##-#
#--#...*.---#
#-$#...*.#$##
#--#######--#
#-$$-$-$-$$-#
#-----------#
#############
Title: 007 Back and Forth
Comment: Avoiding something I had to do.
Previously published: SokobanOnline, Accumulated1
Date: 2015-02-21

###########
#----#----#
#-.*-$-*.-#
#-$**#**$-#
#----+----#
###########
Title: 008 Gil1
Comment: Tried to make a level for Gil Dogans level design contest
Previously published: Accumulated1
Date: 2015-03-28

--#####
--#---##
###-#--#
#--*-#-#
#-*-*--#
##@*---#
-#--####
-####
Title: 009 2x2 Cyclic
Comment: Another level for Gil Dogans competition. I love the design and the puzzle actually took first place for a few days.
Previously published: SokobanOnline, Accumulated1
Date: 2015-03-28

--#####
--#---##
###-#--##
#--*-#--#
#-*-*-#-#
#*-*-*--#
#@*-*---#
#--*--###
#---###
#####
Title: 010 3x3 Cyclic
Comment: Another level for Gil Dogans Sokoban contest. Here the beautifyll version. The actual level for the contest was heavily uglifyed by making til passagevay top right longer.
Previously published: Accumulated1
Date: 2015-03-29

--#######
--#-----#
-##-###-##
##-*-@-*-##
#-*-***-*-#
#--*---*--#
#---###---#
###-----###
--#######
Title: 011 Back To Start 2
Comment: For Gil Dogans Sokoban competition. Nice, isn't it? But low scoring.
Previously published: SokobanOnline.com, Accumulated1
Date: 2015-04-04

-----#####
-#####---#
##...$---###
#-+**##$---#
#-..*-#-$#-#
##$##------#
-#--#-$#####
-#--$--#
-#-----#
-#######
Title: 012 Upper Left Corner, Please
Comment: Start with pushing one block to the upper left corner...
Previously published: SokobanOnline.com
Date: 2015-04-20

-#######
-#--@--#
-#--$--#
##-$.$-##
#-$.$.$-#
#$.$.$.$#
#.$.$.$.#
#-.$.$.-#
##-.$.-##
-#--.--#
-#-----#
-#######
Title: 013 80 Is An Okay Score
Comment: First title was "100 Is An Okay Score" but that was too easy so changed the title.
Previously published: SokobanOnline.com, Accumulated1
Date: 2015-04-24

---###
-###@###
-#--$--#
##-$.$-##
#-$.$.$-#
#$.$.$.$#
#.$.$.$.#
#-.$.$.-#
##-.$.-##
-#--.--#
-###-###
---###
Title: 014 Tighter
Comment: Realised how easy the previous puzzle was.
Previously published: SokobanOnline.com, Accumulated1
Date: 2015-04-25

-----#####
-----#---##
----##-$@-#
---##-$*$-#
--##...$--#
###-.*.-###
#--$*..##
#-$.$-##
#--$-##
#----#
######
Title: 015 More Malicious
Author: Malice+Tyge Fogh
Comment: Thought Malicious #14 was a nice design but a little easy. This one is a little less easy, but not much.
Previously published: SokobanOnline.com, Accumulated1
Date: 2015-04-28

--#####
--#---##
###-*--##
#--$*$--#
#@*...*-#
#--$*$--#
###-.-###
--#---#
--#####
Title: 016 Lazy Saturday
Previously published: SokobanOnline.com, Sokoban.dk, Accumulated1
Date: 2015-05-16

---#####
---#---##
-###-#--##
##--*-#--##
#--*-*-#--#
#-*-*-*-#-#
#*-*-*-*--#
#-*-*-*---#
#-@*-*--###
#---*-###
##---##
-#####
Title: 017 Back To Start 3
Comment: I promise I will not make any bigger levels with this design. At least you will have to look in the collections Sharpen for bigger levels.
Previously published: SokobanOnline.com
Date: 2015-05-16

------#########
------##@##---#
------#-*-----#
---####---##-#####
---#--#-###--#---#
---#------#------#
####--#---#--##-#####
#--##-########--#---#
#------#-----#------#
#--#---#-----#--##-##
##-#####-----#####-##
##-##--#-----#---#--#
#------#-----#------#
#---#--########-##--#
#####-##--#---#--####
---#------#------#
---#---#--##-##--#
---#####-###--####
------#-------#
------#---##--#
------#########
Title: 018 No challenge. Just waste of time
Comment: Nice design but wrong size for Gil Dogans Sokoban contest.
Previously published: SokobanOnline.com, Accumulated1
Date: 2015-05-23

----####
---##--#
---#@*-#
---#-*-#
---#-*-#
---#-*-#
---#-*-#
####-*-#
#---#*-#
#----*-#
###-#--#
-#--##-##
-#------#
-#--#---#
-########
Title: 019 Eight In A Row
Comment: Made for Gil Dogans Sokoban Contest. A mediocre score.
Previously published: SokobanOnline.com, Sokoban.dk(Lines), Accumulated1
Date: 2015-06-19

------####
------#--#
------#--######
------#-$-----#
----###$#---$-#
----#...-###-####
---##.*..-#-$$--#
---#..##..#-----#
---#.*...*$$-$$##
---#-**#.-#-$@-#
#####...-#-$-###
#---####-$$--#
#-$$$--$----##
#----$--#--##
#---########
#####
Title: 020 Not So Difficult Rev
Comment: First version published at SokobanOnline. Discovered a ridicously easy solution. Removed a floor, added a wall, added a floor and moved the sokoban. Still no match for a trained player.
Previously published: SokobanOnline.com., Accumulated1
Date: 2015-06-30

######
#----####
#-$-.-$-#
#-#$.$#-#
#-..*..-#
#-#$.$#-#
#-$-+-$-#
#####---#
----#####
Title: 021 Summer 1
Previously published: SokobanOnline.com, Sokoban.dk (Crosses), Accumulated1
Date: 2015-07-02

###########
#...------#
#######-#-#
#.------#-#
#.$$$$#-#-#
#.----$-#-#
#$#######-#
#@--------#
###########
Title: 022 Timesaver
Comment: Same basic design as level 59 from TIAOAs first collection. Saves you a lot of time.
Previously published: Sokoban.dk, Accumulated1
Date: 2015-07-04

---------####
-#########--#
##--$-----.-##
#--$-$-#-***-#
#@$-$-$#..*..#
##-$-$-#-...-#
-#--$--##-.--#
-##--#########
--####
Title: 023 Summer 2
Comment: Variation from SokobanOnline.com. Made the right side a bit more interesting.
Previously published: SokobanOnline.com, Accumulated1.
Date: 2015-07-03

-----#####
-----#---#
--####-#-##
--#----*--##
###-#-*.*--#
#---#.$#-*-#
#---*-*-*-*#
######-$-#-#
-----#-@---#
-----#######
Title: 024 Pyramid
Comment: Rotated the puzzle 90 deg. clockwise for my collection "Go Right"
Previously published: SokobanOnline.com, Sokoban.dk(Go Right), Accumulated1.
Date: 2015-07-11

----####
----#--#
----#--#
--###--#
###--*-##
#---*-*-###
#--*-*-*--#
###-*-*---#
--##-*-####
---#--##
---#-@#
---####
Title: 025 Less Pain
Comment: Needed an easy one after publishing a remodel from Gil Dogans contest.
Previously published: SokobanOnline.com, Accumulated1.
Date: 2015-07-14

---#
--###
-##-##
##-.-##
#--*--#
#--*--#
#-$*$##
##-*-##
-#-*-#
-#-*-#
-#-*-#
-#-.-#
-#-@-#
-#####
Title: 026 No Pain
Previously published: SokobanOnline.com, Sokoban.dk(Lines), Accumulated1.
Date: 2015-07-14

##########
#--------#
#-*.*.*..#
##$####-##
#--$@$-$-#
#--------#
##########
Title: 027 An In Betweener With No Title Originally
Previously published: Sokoban.dk(Lines) Accumulated1.
Date: 2015-08-02

#############
#------.....#
#------*.*..#
#--######-#$###
#--#--$-$---$-#
#--#-$#-#-#-#-#
####--$---$-$-#
---##@#######-#
---#----------#
---############
Title: 028 No Pain 2 Rev
Comment: Just added a wall to the puzzle originally published at SokobanOnline. Not sure it makes a more interesting puzzle.
Previously published: SokobanOnline.com, Accumulated1.
Date: 2015-08-10

---#####
---#---##
-###-#--##
-#--*-#--##
##-#-*-#--#
#---*-*-#-#
#@-*-*-*--#
##--*---###
-#####--#
-----####
Title: 029 Last One For Free
Comment: Published 25 levels on SokobanOnline.com. Had to pay 0.99$ for an upgrade to pro memeber to publish more. But the site gave me a free ticket.
Previously published: SokobanOnline.com, Accumulated1.
Date: 2015-08-10

---#####
--##---#
-##--#-###
##--#-*--##
#--#-*-*--#
#-#-*-*-*-###
#--*-#-#-*--#
##--*-*-*---#
-##--*-*---##
--##--*--@##
---########
Title: 030 Back To Start 44 Variation
Comment: Could be a plain 4x4 cyclic puzzle. But you dont need to move all the blocks in many cyclic puzzles. The trick is to figure out which ones
Previously published: Accumulated1.
Date: 2015-08-11

-------#####
########---##
#--##--$$---#
#--------#$-#
#-$##-#--#-###
##-#--####---#
-#-#-#.-.#*#-#
-#-#-#.*.*.#-#
-#--$$-#-.*-@#
-#---####---##
-#--##--#####
-####
Title: 031 Not 6x2
Comment: Wanted to make a level with a 6*2 goal. Ended up like this.
Previously published: SokobanOnline.com, Accumulated1.
Date: 2015-08-15

--#########
--#---.---#
--#---.---#
--#-##.####
--#-#-.---###
###-#-.-#---#
#-$$$$*$$$$-#
#---#-.-#---#
###--#.-#####
--##--+##
---#####
Title: 032 Nine In A Row
Previously published: SokobanOnline.com, Sokoban.dk(Lines), Accumulated1.
Date: 2015-08-19

####-####
#--###--#
#--$----#
#-$#.#--#
##--.#-##
-#$#.#-#
-#--.#-#
-#$#.#-##
-#---#--#
-#$----@#
-#--#####
-####
Title: 033 Five In A Row
Previously published: SokobanOnline.com, Sokoban.dk(Lines), Accumulated1.
Date: 2015-08-22

--#####
--#---#
###---###
#--***--#
#--*@*--#
###***--#
--#---###
--#---#
--#####
Title: 034 Nice And Not So Easy
Comment: Checked nobody ever made this puzzle before.
Previously published: SokobanOnline.com, Accumulated1.
Date: 2015-08-24

--######
--#----#
###--#-###
#--****--#
#--*@-*--#
#--*--*--#
##########
Title: 035 Page Two
Comment: A beautiful simple design. A favorite of mine.
Previously published: SokobanOnline.com, Accumulated1.
Date: 2015-08-25

----------#
----------##
----------###
----------#-##
###########--##
#-------------##
#.**********$--##
#--------@---###
###########--##
----------#-##
----------###
----------##
----------#
Title: 036 Next
Comment: You can find 100.000+ sokoban levels on the net and still nobody ever made this simple design. Amazing.
Previously published: SokobanOnline.com, Sokoban.dk(Go Right), Accumulated1.
Date: 2015-09-05

---####
####--####
#-$-.*-$-#
#-#-**-#-#
#-#-..-#-#
#---##$--#
###--@-###
--######
Title: 037 2x3
Comment: Idea from David Hollands Maelstrom 18.
Previously published: Accumulated1.
Date: 2015-09-10

-----#######
-----#-----##
-----#-.----#
-######.#-#-#
##---##.#---#
#---$-#.#---#
#-$$$-#.#---#
#--@$-#.----#
#-$#$--.#---#
#---$-#.#####
#####---#
----#####
Title: 038 Elegance
Comment: An elegant unexpected solution just popped out.
Previously published: Sokoban.dk(Lines) Accumulated1.
Date: 2015-09-22

-#######
-#-----#
##$#-#$####
#--.....*-#
#-#$##$#$-#
#------#--#
###-#@##-##
--#------#
--########
Title: 039 An Easy Six
Comment: Wont keep you sleepless.
Previously published: Accumulated1.
Date: 2015-09-27

#########
#---#---#
#-#---#-#
#-$$.$$@#
##..*..##
#-$-.---#
#-#-#$#-#
#---#---#
#########
Title: 040 5x3
Previously published: Accumulated1.
Date: 2015-10-03

------#
-----###
------#
-----###
----##.##
---##.$.##
--##-$.$-##
-##-.-$-.-##
##-*-.#.-*-##
#-$-*###*-$-#
#--$--#--$--#
#-----#--@--#
#############
Title: 041 Happy Christmas
Comment: Idea from "Prayers" by Bodler. Added a cross on top and published at SokobanOnline 2015-12-24 with the title "Happy Christmas"
Previously published: SokobanOnline.com, Sokoban.dk(Remodels1), Accumulated1.
Date: 2015-10-03

-----#####
-----#---#
----##-#-##
----#-----#######
----#-----#-----#
----#-##.##-$-#-#
---##--#.####$--#
-#####-#....$-$-#
##---#....##-$--#
#----#$##.##$##-#
#-$----$-*-#@---#
#-#---$----######
#-#####$####
#-------#
#########
Title: 042 Whatever
Comment: Decided to do something with a crossshaped goal.
Previously published: Sokoban.dk (Crosses), DrFogh-Accumulated 1
Date: 2014-10-05

--#####
--#-.-#
--#$.$#
--#-.-#
--#-.-#
###$.$###
#--$.$--#
#---*---#
###-@-###
--#####
Title: 043 So Simple 1
Comment: And still never made before.
Previously published: SokobanOnline.com
Date: 2015-10-10

--#####
--#-.-#
--#$.$#
--#-.-#
--#$.$#
--#-.-#
--#-.-#
###$.$###
#--$.$--#
#---*---#
###-@-###
--#####

Title: 044 So Simple 2
Comment: A little higher
Date: 2015-10-10

--#####
--#-.-#
--#$.$#
--#-.-#
--#$.$#
--#-.-#
--#$.$#
--#-.-#
--#$.$#
--#-.-#
--#-.-#
###$.$###
#--$.$--#
#---*---#
###-@-###
--#####
Title: 045 So Simple 4
Comment: This design can be expanded infinitely. From this puzzle and further YASS couldn't solve it.
Previously published: Sokoban.dk(Lines)
Date: 2015-11-13

--------#####
#########---#
#----.....#-#
#---@$------#
##-#######-##
-#-----#--$#
-###-#$#---#
---#---$-$##
---####---#
-----######
Title: 046 Row514
Comment: The title? Goal five in a row. Layout no 14 was final level.
Previously published: Sokoban.dk(Lines)
Date: 2015-09-25

----#####
----#---#
----#$.$#
----#-.-#
#####$.$#####
#-$-$-.-$-$-#
#-....@....-#
#-$-$-.-$-$-#
#####$.$#####
----#-.-#
----#$.$#
----#-.-#
----#$.$#
----#-.-#
----#$.$#
----#---#
----#####
Title: 047 Cross
Previously published: SokobanOnline.com, Sokoban.dk (Crosses)
Date: 2015-10-18

46 Cross. Now With Centerblock

----#####
----#---#
----#$.$#
----#-.-#
#####$.$#####
#-$-$-+-$-$-#
#-....*....-#
#-$-$-.-$-$-#
####-$.$-####
---##-.-##
----#$.$#
----#-.-#
----#$.$#
----#-.-#
----#$.$#
----#---#
----#####
Title: 048 Cross. Now With Centerblock
Previously published: SokobanOnline.com, Sokoban.dk (Crosses)
Date: 2015-10-18

#########
#--.-.--#
#--$-$--#
##*****##
#--$-$--#
#--.@.--#
#########
Title: 049 Nakarev
Comment: Thought it was inspiration from Nakaxsomething, but it was somewhere else.
Previously published: SokobanOnline.com
Date: 2015-11-12

--------#####
--------#---##
--#####-#-$--#
--#---####-#-###
--#-#...-$--$--#
###-#.#.#$$$-#-#
#---#...#-#----#
#-#-#...#-#$$###
#----...#@$---#
######-##$$---#
-----#--#-##-##
-----#-$#-$--#
-----#--$---##
-----##---###
------#####
Title: 050 Dev42
Previously published: Sokoban.dk
Date: 2015-11-19
"""


@dataclass(frozen=True, slots=True)
class ParsedLevel:
    index: int
    title: str
    board_lines: tuple[str, ...]


def is_board_line(line: str) -> bool:
    return bool(line) and set(line) <= BOARD_CHARS


def parse_collection(text: str) -> list[ParsedLevel]:
    levels: list[ParsedLevel] = []
    current_board: list[str] = []
    current_title: str | None = None
    collecting_board = False

    for raw_line in text.splitlines():
        line = raw_line.rstrip("\n")

        if is_board_line(line):
            if not collecting_board and current_board and current_title is not None:
                levels.append(
                    ParsedLevel(
                        index=len(levels) + 1,
                        title=current_title,
                        board_lines=tuple(current_board),
                    )
                )
                current_board = []
                current_title = None

            collecting_board = True
            current_board.append(line)
            continue

        collecting_board = False

        if line.startswith("Title:"):
            current_title = line.split("Title:", 1)[1].strip()

    if current_board:
        levels.append(
            ParsedLevel(
                index=len(levels) + 1,
                title=current_title or f"Untitled {len(levels) + 1:03d}",
                board_lines=tuple(current_board),
            )
        )

    return levels


def _neighbors(position: tuple[int, int]) -> list[tuple[int, int]]:
    row, col = position
    return [(row + dr, col + dc) for dr, dc in DIRECTIONS]


def _outside_padding_positions(grid: list[str]) -> set[tuple[int, int]]:
    rows = len(grid)
    cols = max(len(row) for row in grid)
    padded_grid = [row.ljust(cols, OUTSIDE_CHAR) for row in grid]
    outside: set[tuple[int, int]] = set()
    frontier = deque()

    for row in range(rows):
        for col in (0, cols - 1):
            if padded_grid[row][col] == OUTSIDE_CHAR and (row, col) not in outside:
                outside.add((row, col))
                frontier.append((row, col))

    for col in range(cols):
        for row in (0, rows - 1):
            if padded_grid[row][col] == OUTSIDE_CHAR and (row, col) not in outside:
                outside.add((row, col))
                frontier.append((row, col))

    while frontier:
        position = frontier.popleft()
        for neighbor in _neighbors(position):
            row, col = neighbor
            if row < 0 or row >= rows or col < 0 or col >= cols:
                continue
            if padded_grid[row][col] != OUTSIDE_CHAR:
                continue
            if neighbor in outside:
                continue

            outside.add(neighbor)
            frontier.append(neighbor)

    return outside


def build_state(level: ParsedLevel) -> SokobanState:
    grid = list(level.board_lines)
    rows = len(grid)
    cols = max(len(row) for row in grid)
    padded_grid = [row.ljust(cols, OUTSIDE_CHAR) for row in grid]
    outside = _outside_padding_positions(grid)

    player = None
    boxes = []
    goals = []
    walls = []
    floor = set()

    for row in range(rows):
        for col in range(cols):
            position = (row, col)
            cell = padded_grid[row][col]

            if cell == "#":
                walls.append(position)
                continue

            if cell == OUTSIDE_CHAR and position in outside:
                continue

            if cell in {OUTSIDE_CHAR, ".", "$", "*", "@", "+"}:
                floor.add(position)

            if cell in {".", "*", "+"}:
                goals.append(position)
            if cell in {"$", "*"}:
                boxes.append(position)
            if cell in {"@", "+"}:
                player = position

    if player is None:
        raise ValueError(f"Level {level.index:03d} ({level.title}) has no player.")

    layout = BoardLayout.from_explicit_floor(
        floor_pos=floor,
        goals_pos=goals,
        walls_pos=walls,
    )

    return SokobanState(
        player,
        boxes,
        goals,
        walls,
        board_layout=layout,
    )


def moved_box_positions(parent: SokobanState, child: SokobanState) -> set[tuple[int, int]]:
    return set(child.boxes - parent.boxes)


def validate_level(level: ParsedLevel, render: bool = False) -> list[str]:
    state = build_state(level)
    layout = state.get_board_layout()
    analysis = state.get_static_deadlock_info()
    successors = state.get_successors()
    issues: list[str] = []

    if not state.goals <= layout.floor:
        issues.append("goals are not a subset of floor")
    if not state.boxes <= layout.floor:
        issues.append("boxes are not a subset of floor")
    if state.player not in layout.floor:
        issues.append("player is not on floor")
    if state.goals & analysis.forbidden_box_tiles:
        issues.append("some goals were marked as forbidden")
    if not state.goals <= analysis.reachable_box_tiles:
        issues.append("some goals were not marked as reachable box tiles")
    if analysis.reachable_box_tiles & analysis.forbidden_box_tiles:
        issues.append("reachable and forbidden sets overlap")

    expected_deadlock = any(
        box not in state.goals and box in analysis.forbidden_box_tiles
        for box in state.boxes
    )
    if state.has_static_deadlock() != expected_deadlock:
        issues.append("has_static_deadlock() is inconsistent with forbidden tiles")

    for action, successor in successors:
        moved_boxes = moved_box_positions(state, successor)
        if not moved_boxes:
            continue

        moved_box = next(iter(moved_boxes))
        if moved_box not in successor.goals and moved_box in successor.get_static_deadlock_info().forbidden_box_tiles:
            issues.append(f"successor {action} moved a box into a forbidden tile")

    summary = (
        f"[{'OK' if not issues else 'FAIL'}] "
        f"{level.index:03d} {level.title} | "
        f"boxes={len(state.boxes)} goals={len(state.goals)} "
        f"reachable={len(analysis.reachable_box_tiles)} "
        f"forbidden={len(analysis.forbidden_box_tiles)} "
        f"successors={len(successors)}"
    )
    print(summary)

    if render:
        print("Board:")
        print(state.render())
        print("Static analysis:")
        print(state.render_static_analysis())

    for issue in issues:
        print(f"  - {issue}")

    return issues


def load_collection_text(collection_file: Path | None) -> str:
    if collection_file is None:
        return ORIGINAL01_COLLECTION
    return collection_file.read_text(encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(
        description="Run static deadlock analysis against the Original01 collection.",
    )
    parser.add_argument(
        "--collection-file",
        type=Path,
        default=None,
        help="Optional path to a collection file. Defaults to the embedded Original01 text.",
    )
    parser.add_argument(
        "--render-all",
        action="store_true",
        help="Render the original board and static analysis for every level.",
    )
    parser.add_argument(
        "--levels",
        type=int,
        nargs="*",
        default=None,
        help="Optional 1-based level numbers to run. Defaults to the full collection.",
    )
    args = parser.parse_args()

    collection_text = load_collection_text(args.collection_file)
    levels = parse_collection(collection_text)

    if len(levels) != DEFAULT_EXPECTED_LEVELS:
        raise SystemExit(
            f"Expected {DEFAULT_EXPECTED_LEVELS} levels, parsed {len(levels)}."
        )

    selected_level_numbers = set(args.levels or [])
    selected_levels = [
        level
        for level in levels
        if not selected_level_numbers or level.index in selected_level_numbers
    ]

    if not selected_levels:
        raise SystemExit("No levels matched the requested --levels filter.")

    total_issues = 0
    for level in selected_levels:
        issues = validate_level(level, render=args.render_all)
        total_issues += len(issues)

    if total_issues:
        raise SystemExit(
            f"Static deadlock validation finished with {total_issues} issue(s)."
        )

    print(f"Validated {len(selected_levels)} levels from Original01 with no issues.")


if __name__ == "__main__":
    main()
